### PR TITLE
Add accelerator <Ctrl>Q

### PR DESCRIPTION
**Pull request by ayushnawal**

### CODE REVIEW

**Comment by quozl** [comment]
Isn't needed, as it is already the default, see https://github.com/sugarlabs/sugar-toolkit-gtk3/blob/88adb38a4241aa5423a9cefae9b4b11305bb61c5/src/sugar3/activity/widgets.py#L85

Also, it should not be processed by gettext.

**Comment by ayushnawal** [comment]
Oh, I see.

I didn't check `sugar-toolkit-gtk3`.

Some old activities still include this with the stop button, so I added the same when I was going through the source files.

**Comment by quozl** [comment]
Yes, some old activities have this extra line, but it was added to the toolkit so it is not needed.

**Comment by Aniket21mathur** [comment]
@ayushnawal instead you can remove accelerator from those activities, as it  is already present with the toolkit.

**Pull request closed without merging**
